// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectProjectDirectory(arg1) {
  return window['go']['ui']['API']['SelectProjectDirectory'](arg1);
}
