// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {terminal} from '../models';

export function Resize(arg1:number,arg2:number,arg3:number):Promise<void>;

export function Start(arg1:number):Promise<terminal.Handle>;

export function Stop(arg1:number):Promise<void>;

export function Write(arg1:number,arg2:string):Promise<void>;
