// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Resize(arg1, arg2, arg3) {
  return window['go']['terminal']['API']['Resize'](arg1, arg2, arg3);
}

export function Start(arg1) {
  return window['go']['terminal']['API']['Start'](arg1);
}

export function Stop(arg1) {
  return window['go']['terminal']['API']['Stop'](arg1);
}

export function Write(arg1, arg2) {
  return window['go']['terminal']['API']['Write'](arg1, arg2);
}
