// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAttachment(arg1) {
  return window['go']['attachments']['API']['DeleteAttachment'](arg1);
}

export function SaveClipboardImage(arg1, arg2) {
  return window['go']['attachments']['API']['SaveClipboardImage'](arg1, arg2);
}
