// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {projects} from '../models';

export function DeleteProject(arg1:number):Promise<void>;

export function ListProjects():Promise<Array<projects.ProjectDTO>>;

export function MarkProjectOpened(arg1:number):Promise<void>;

export function RegisterProject(arg1:projects.RegisterProjectRequest):Promise<projects.ProjectDTO>;
