// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProject(arg1) {
  return window['go']['projects']['API']['DeleteProject'](arg1);
}

export function ListProjects() {
  return window['go']['projects']['API']['ListProjects']();
}

export function MarkProjectOpened(arg1) {
  return window['go']['projects']['API']['MarkProjectOpened'](arg1);
}

export function RegisterProject(arg1) {
  return window['go']['projects']['API']['RegisterProject'](arg1);
}
