// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['agents']['API']['Cancel'](arg1);
}

export function CreatePullRequest(arg1) {
  return window['go']['agents']['API']['CreatePullRequest'](arg1);
}

export function DeleteThread(arg1) {
  return window['go']['agents']['API']['DeleteThread'](arg1);
}

export function EmitThreadDiffUpdate(arg1) {
  return window['go']['agents']['API']['EmitThreadDiffUpdate'](arg1);
}

export function GetThread(arg1) {
  return window['go']['agents']['API']['GetThread'](arg1);
}

export function ListThreadFileDiffs(arg1) {
  return window['go']['agents']['API']['ListThreadFileDiffs'](arg1);
}

export function ListThreads(arg1) {
  return window['go']['agents']['API']['ListThreads'](arg1);
}

export function LoadThreadConversation(arg1) {
  return window['go']['agents']['API']['LoadThreadConversation'](arg1);
}

export function LoadThreadConversationPage(arg1) {
  return window['go']['agents']['API']['LoadThreadConversationPage'](arg1);
}

export function RenameThread(arg1, arg2) {
  return window['go']['agents']['API']['RenameThread'](arg1, arg2);
}

export function Send(arg1) {
  return window['go']['agents']['API']['Send'](arg1);
}
