// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agents} from '../models';

export function Cancel(arg1:string):Promise<agents.CancelResponse>;

export function CreatePullRequest(arg1:number):Promise<string>;

export function DeleteThread(arg1:number):Promise<void>;

export function EmitThreadDiffUpdate(arg1:number):Promise<void>;

export function GetThread(arg1:number):Promise<agents.ThreadDTO>;

export function ListThreadFileDiffs(arg1:number):Promise<Array<agents.FileDiffStatDTO>>;

export function ListThreads(arg1:number):Promise<Array<agents.ThreadDTO>>;

export function LoadThreadConversation(arg1:number):Promise<Array<agents.ConversationEntryDTO>>;

export function RenameThread(arg1:number,arg2:string):Promise<agents.ThreadDTO>;

export function Send(arg1:agents.MessageRequest):Promise<agents.StreamHandle>;
