// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agents} from '../models';
import {projects} from '../models';

export function CancelAgentStream(arg1:string):Promise<agents.CancelResponse>;

export function DeleteAttachment(arg1:string):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteThread(arg1:number):Promise<void>;

export function GetThread(arg1:number):Promise<agents.ThreadDTO>;

export function Greet(arg1:string):Promise<string>;

export function ListProjects():Promise<Array<projects.ProjectDTO>>;

export function ListThreads(arg1:number):Promise<Array<agents.ThreadDTO>>;

export function LoadThreadConversation(arg1:number):Promise<Array<agents.ConversationEntryDTO>>;

export function MarkProjectOpened(arg1:number):Promise<void>;

export function RegisterProject(arg1:projects.RegisterProjectRequest):Promise<projects.ProjectDTO>;

export function RenameThread(arg1:number,arg2:string):Promise<agents.ThreadDTO>;

export function SaveClipboardImage(arg1:string,arg2:string):Promise<string>;

export function SelectProjectDirectory(arg1:string):Promise<string>;

export function SendAgentMessage(arg1:agents.MessageRequest):Promise<agents.StreamHandle>;
