// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAgentStream(arg1) {
  return window['go']['main']['App']['CancelAgentStream'](arg1);
}

export function CreatePullRequest(arg1) {
  return window['go']['main']['App']['CreatePullRequest'](arg1);
}

export function DeleteAttachment(arg1) {
  return window['go']['main']['App']['DeleteAttachment'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteThread(arg1) {
  return window['go']['main']['App']['DeleteThread'](arg1);
}

export function GetThread(arg1) {
  return window['go']['main']['App']['GetThread'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListThreadFileDiffs(arg1) {
  return window['go']['main']['App']['ListThreadFileDiffs'](arg1);
}

export function ListThreads(arg1) {
  return window['go']['main']['App']['ListThreads'](arg1);
}

export function LoadThreadConversation(arg1) {
  return window['go']['main']['App']['LoadThreadConversation'](arg1);
}

export function MarkProjectOpened(arg1) {
  return window['go']['main']['App']['MarkProjectOpened'](arg1);
}

export function RegisterProject(arg1) {
  return window['go']['main']['App']['RegisterProject'](arg1);
}

export function RenameThread(arg1, arg2) {
  return window['go']['main']['App']['RenameThread'](arg1, arg2);
}

export function ResizeThreadTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeThreadTerminal'](arg1, arg2, arg3);
}

export function SaveClipboardImage(arg1, arg2) {
  return window['go']['main']['App']['SaveClipboardImage'](arg1, arg2);
}

export function SelectProjectDirectory(arg1) {
  return window['go']['main']['App']['SelectProjectDirectory'](arg1);
}

export function SendAgentMessage(arg1) {
  return window['go']['main']['App']['SendAgentMessage'](arg1);
}

export function StartThreadTerminal(arg1) {
  return window['go']['main']['App']['StartThreadTerminal'](arg1);
}

export function StopThreadTerminal(arg1) {
  return window['go']['main']['App']['StopThreadTerminal'](arg1);
}

export function WriteThreadTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteThreadTerminal'](arg1, arg2);
}
